package com.gid.utility;

public class Constant {
    public static final String CLIENT = "Client_EDC_154";
    public static final String MANUFACTURER = "Manufacturer_EDC_154";
    public static final String TERRITORIES1 = "Trr_EDC_02_154";
    public static final String TERRITORIES2 = "Great Britain";
    public static final String LP = "LP_EDC_154";
    public static final String HP1 = "Newcastle";
    public static final String HP2 = "Halewood";
    public static final String CLIENT_ADD_TERRITORY_LP = "Jaguar Land Rover Client";
    public static final String TERRITORY_ADD_TERRITORY_LP = "Ireland";
    public static final String HANDOVER_POINTS_ADD_TERRITORY_LP = "Dublin";
    public static final String INVALID_LOGIN_VALIDATION_MESSAGE = "Invalid Credentials. Please Try Again";
    public static final String COMPANY_NAME_VALIDATION_MESSAGE = "Please Enter Your Company Name";
    public static final String COMPANY_EMAIL_VALIDATION_MESSAGE = "Please Enter Your Company Email";
    public static final String COMPANY_ADDED_SUCCESS_MESSAGE = "Company added successfully. Please enter additional information";
    public static final String DAMAGE_TYPE_VALIDATION_MESSAGE = "Please Enter Damage Type";
    public static final String CLIENT_CODE_VALIDATION_MESSAGE = "Please Enter Client Code";
    public static final String OEM_CODE_VALIDATION_MESSAGE = "Please Enter OEM Code";
    public static final String DUPLICATE_CLIENT_CODE_VALIDATION_MESSAGE = "Client Code Already Exist";
    public static final String DUPLICATE_OEM_CODE_VALIDATION_MESSAGE = "OEM Code Already Exist";
    public static final String DAMAGE_LOCATION_VALIDATION_MESSAGE = "Please Enter Damage Location";
    public static final String DAMAGE_SEVERITY_VALIDATION_MESSAGE = "Please Enter Damage Severity";
    public static final String ENTRY_EDITED_SUCCESS_MESSAGE = "Entry edited successfully";
    public static final String ENTRY_SAVED_SUCCESS_MESSAGE = "Your changes have been successfully saved!";
    public static final String TERRITORIES_VALIDATION_MESSAGE = "Please Select a Territory";
    public static final String HANDOVER_POINTS_VALIDATION_MESSAGE = "Select Handover Points";
    public static final String USER_FIRST_NAME_VALIDATION_MESSAGE = "Please Enter FirstName";
    public static final String USER_LAST_NAME_VALIDATION_MESSAGE = "Please Enter LastName";
    public static final String USER_EMAIL_VALIDATION_MESSAGE = "Please Enter Email";
    public static final String USER_PASSWORD_VALIDATION_MESSAGE = "Please Enter Password";
    public static final String USER_CONFIRM_PASSWORD_VALIDATION_MESSAGE = "Password Does Not Match";
    public static final String ENTRY_ADDED_SUCCESS_MESSAGE = "Entry added successfully";
    public static final String CONTRACT_NAME_VALIDATION_MESSAGE = "Please Enter Contract Name";
    public static final String CONTRACT_TYPE_VALIDATION_MESSAGE = "Please Select Contract Type";
    public static final String CLIENT_NAME_VALIDATION_MESSAGE = "Please Select Client";
    public static final String ASSOCIATED_MANUFACTURER_VALIDATION_MESSAGE = "Please Select Associated Manufacturer";
    public static final String TERRITORY_VALIDATION_MESSAGE = "Please Select Territories";
    public static final String HANDOVER_POINT_VALIDATION_MESSAGE = "Please Selcet Handover Points";
    public static final String LP_VALIDATION_MESSAGE = "Please Select LP";
    public static final String TERRITORIES_DEALER_CLIENT_LP_VALIDATION_MESSAGE = "Please Add Client";
    public static final String TERRITORIES_DEALER_VALIDATION_MESSAGE = "Please Add Territory";
    public static final String TERRITORY_NME_VALIDATION_MESSAGE = "Please Enter Territory Name";
    public static final String HANDOVER_POINT_NAMES_VALIDATION_MESSAGE = "Please Add Handover Point";
    public static final String HANDOVER_POINT_NAMES_LP_VALIDATION_MESSAGE = "Please Add Handover Points";
    public static final String HANDOVER_POINT_NAME_VALIDATION_MESSAGE = "Please add handover point";
    public static final String TERRITORY_ADDED_CONFIRMATION_MESSAGE = "Territory added successfully";
    public static final String INSPECTION_ENTRY_EDITED_SUCCESS_MESSAGE = "Entry Edited Successfully";
    public static final String RESTAPI_BASEURL = "https://test.api.trivand.com";
    public static final String BULK_EDIT_EXPORT_TO_CSV_SUCCESS_MESSAGE = "Report generation is in progress. You will receive an email with the report link shortly. It's safe to close the window now.";

}
